### ISSUE TITLE
Optional JSON sorter

### ISSUE THREAD

**Issue by A11v1r15** [WinPlay02/GitCraft#2]
Add an argument so JSON files pass through a sorter algorithm before committing so it has less "false positive diffs" and actual changes to the data can be seen more clearly. Applicable for the SNBT files too?

**Comment by WinPlay02** [comment]
This is now implemented. Sorting can be enabled with the `--sort-json` flag and only affects JSON objects, as arrays are already ordered.
SNBT files are not covered here.
